[project]
name = "fast-check-test"
authors = ["LNow"]
telemetry = false

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }